Format code hello triangle
opentk/opentk.net pull request #48
Opened 2020-09-27 04:15 UTC by Mautar55

GL.BindBuffer(BufferTarget.ArrayBuffer, VertexBufferObject);

GL.BufferData(BufferTarget.ArrayBuffer, vertices.Length * sizeof(float), vertices, BufferUsageHint.StaticDraw);

Those are now are in the proper frame.

2020-10-04 12:02 UTC, frederikja163 requested changes
You need to remove the old code blocks that were there before im gonna merge this.

2020-10-04 12:02 UTC, frederikja163 commented on learn/chapter1/2-hello-triangle.md
>  `GL.BufferData(BufferTarget.ArrayBuffer, vertices.Length * sizeof(float), vertices, BufferUsageHint.StaticDraw);`
Remove the code blocks from this line before we can merge

2020-10-04 12:02 UTC, frederikja163 commented on learn/chapter1/2-hello-triangle.md
>  `GL.BindBuffer(BufferTarget.ArrayBuffer, VertexBufferObject);`
Remove the code blocks from this line before we can merge

2022-06-05 13:51 UTC, merged

2022-06-05 13:51 UTC, NogginBops commented
Thanks for the PR @Mautar55!
Sorry for letting it go unmerged for so long. :)